### ISSUE TITLE
Number of GPUs for training

### ISSUE THREAD

**Issue by timmeinhardt** [PRBonn/MaskPLS#12]
Hello,

could you share on how many GPUs you trained your models?  The `N_GPUS: -1` config adapts automatically and therefore obfuscates this training detail.

Thank you!!!

**Comment by rmarcuzzi** [comment]
Hi!
We trained with a single GPU. However, you could change that number and train on multiple ones.

**Comment by timmeinhardt** [comment]
Cool. thanks for the info!

**Comment by hphnngcquan** [comment]
> Hi! We trained with a single GPU. However, you could change that number and train on multiple ones.

Do you remember how long it took to train one epoch?

**Comment by rmarcuzzi** [comment]
Hi!
I don't remember exactly but it should be a couple of hours, less than 4.

**Comment by hvk280194** [comment]
Hello rmarcuzzi,

I am testing the model by training for all 10 sequences. It is taking around 4hrs to train for just 1 epoch. 
As u have mentioned above that it took less than 4hrs. Is it for 1 epoch or 100 epochs?

**Comment by hvk280194** [comment]
Hello rmarcuzzi,

Since 1 epoch took around 4 hrs to train. So, did you train the model for 100 epoch which is like 16days of training? 
ALso anyway to speed up the things?

Thanks

**Comment by rmarcuzzi** [comment]
Hi! 
The training took 4h per epoch but we didn't need to train to the full 100 epochs since the performance saturated before.
To speed up the training you can use the pretrained weights of the backbone to not start from scratch but rather from a network that already gives you some good semantics.
To further speed up the training you could use multiple GPUs, subsample more the point cloud [here](https://github.com/PRBonn/MaskPLS/blob/84881ba83f2f2e846cbded677544993d0c8ecd76/mask_pls/config/model.yaml#L39) and you could think about not running validation every epoch.

I hope that helps!
